services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456Aa@
      POSTGRES_DB: subscriptiondb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  subscriptionservice:
    build:
      context: .
      dockerfile: SubscriptionService/Subscription.API/Dockerfile
    container_name: subscriptionservice.api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5001
      ConnectionStrings__SubscriptionConnectionString: "Host=postgres;Port=5432;Database=subscriptiondb;Username=admin;Password=123456Aa@"
      RabbitMq__Host: "rabbitmq"
      RabbitMq__User: "guest"
      RabbitMq__Pass: "guest"
    depends_on:
    - postgres
    - rabbitmq
    ports:
    - "5001:5001"

volumes:
  pgdata:
